In [ ]:
#Rachit Manandhar
#2501387
#np03cs4a240053

Problem - 1: Array Creation:

In [20]:
#1
import numpy as np

arr = np.zeros((2,2))

In [14]:
#2
arr = np.ones((4,2))

In [16]:
#3
def fill_arr(r,c,value):
    return np.full((r,c),value)

fill_arr(4,2,5)

array([[5, 5],
       [5, 5],
       [5, 5],
       [5, 5]])

In [17]:
#4
def fill_zero_arr(arr):
    return np.zeros_like(arr)

arr1 = [[1,2],[3,4],[5,6]]
fill_zero_arr(arr1)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [31]:
#5
def fill_zero_arr(arr):
    return np.ones_like(arr)

arr1 = [[1,2],[3,4],[5,6]]
fill_zero_arr(arr1)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [30]:
#6
new_list = [1,2,3,4]
converted_array = np.array(new_list)

converted_array

array([1, 2, 3, 4])

Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [32]:
#1
values_array = np.arange(10,50)

values_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [33]:
#2
value_array = np.arange(0,9)
matrix = value_array.reshape(3,3)

matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
#3
identity_matrix = np.eye(3)

identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
#4
random_array = np.random.random(30)
mean = random_array.mean()

print("Array: \n", random_array)
print("Mean: ", mean.item())

Array: 
 [0.45172939 0.88032156 0.82885685 0.15340117 0.91084189 0.40059891
 0.65352789 0.75071145 0.13829491 0.84365462 0.0156444  0.20046423
 0.71772985 0.54740898 0.8942947  0.6331739  0.90401563 0.17535167
 0.02669087 0.96468263 0.2438009  0.4094226  0.76203034 0.50206664
 0.75743972 0.47456379 0.74381507 0.33894034 0.20255851 0.71145365]
Mean:  0.5412495686446029


In [37]:
#5
array = np.random.random((10,10))
minimum = array.min()
maximum = array.max()

print("Array: \n", array)
print("Minimum value: ", minimum)
print("Maximum value: ", maximum)

Array: 
 [[0.99280765 0.19374276 0.25526941 0.08222798 0.37189245 0.77138122
  0.53902634 0.17534817 0.76984584 0.68631294]
 [0.14892245 0.63025686 0.39170285 0.99192335 0.6510147  0.29921297
  0.19294516 0.94949024 0.91994054 0.82870788]
 [0.53313222 0.18380768 0.91449856 0.82576628 0.83715377 0.95919817
  0.4875816  0.65121577 0.00209605 0.14085913]
 [0.0374711  0.5672591  0.31234684 0.63796811 0.5479888  0.59233251
  0.09315783 0.46272155 0.89229877 0.97043226]
 [0.05146472 0.16584296 0.37448475 0.3904944  0.17322626 0.09326632
  0.45820423 0.48414121 0.5582054  0.32307356]
 [0.50790122 0.49298639 0.0483749  0.56445625 0.12805952 0.63388347
  0.86005699 0.19874032 0.51721809 0.90438104]
 [0.29112611 0.53193645 0.08232205 0.39619842 0.97968385 0.3499709
  0.48978801 0.79497619 0.80521722 0.45630493]
 [0.61051636 0.37772303 0.72305338 0.18351246 0.99974463 0.23709095
  0.57890865 0.62562103 0.85364359 0.73305669]
 [0.25573838 0.15029147 0.31162966 0.08261519 0.70434113 0.22518721
  0.

In [39]:
#6
zero_array = np.zeros(10)
print("Array before changing the 5th element: ", zero_array)

zero_array[4] = 1
print("Array after changing the 5th element: ", zero_array)

Array before changing the 5th element:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array after changing the 5th element:  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [42]:
#7
arr = np.array([1,2,0,0,4,0])
reversed_arr = arr[::-1]

print("Array reversed is: ", reversed_arr)

Array reversed is:  [0 4 0 0 2 1]


In [45]:
#8
array = np.ones((5, 5))
array[1:-1, 1:-1] = 0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [47]:
#9
array = np.zeros((8,8))
array[1::2, ::2] = 1
array[::2, 1::2] = 1

array

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [48]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

In [50]:
#1
print(x+y)

[[ 6  8]
 [10 13]]


In [51]:
#2
print(x-y)

[[-4 -4]
 [-4 -3]]


In [52]:
#3
print(x*6)

[[ 6 12]
 [18 30]]


In [53]:
#4
print(y ** 2)

[[25 36]
 [49 64]]


In [55]:
#5
print ("Dot product between v and w: ", np.dot(v,w))
print ("Dot product between x and v: ", np.dot(x,v))
print ("Dot product between x and y: ", np.dot(x,y))

Dot product between v and w:  219
Dot product between x and v:  [29 77]
Dot product between x and y:  [[19 22]
 [50 58]]


In [58]:
#6
print("x and y along row: \n", np.concatenate((x,y)))
print("\n\nv and w along column: \n", np.concatenate((v,w)))

x and y along row: 
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]


v and w along column: 
 [ 9 10 11 12]


In [60]:
#7
np.concatenate((x,v))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

We get an error here because x has shape (2,2) while v has shape (2,). Since these arrays have different dimensionality they cannot be concatenated unless both have the same dimensions.

Problem - 4: Matrix Operations:

In [62]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

In [63]:
#1.1

A_inv = np.linalg.inv(A)
result = A @ A_inv
result = np.round(result).astype(int)

identity = np.eye(2, dtype = int)

print("A * A^-1 =\n", result, "\nI =\n", identity)
if (np.array_equal(result, identity)):
  print("A * A^-1 = I")

A * A^-1 =
 [[1 0]
 [0 1]] 
I =
 [[1 0]
 [0 1]]
A * A^-1 = I


In [66]:
# 1.2

AB = A @ B
BA = B @ A

print("AB =\n", AB, "\n\nBA =\n", BA)
print("\n")
print("A * B = B * A:", np.array_equal(AB, BA))

AB =
 [[23 13]
 [51 29]] 

BA =
 [[36 44]
 [13 16]]


A * B = B * A: False


In [67]:
#1.3

LHS = (A @ B).T
RHS = B.T @ A.T

print("LHS =\n", LHS, "\nRHS =\n", RHS)
if (np.array_equal(LHS, RHS)):
  print("(A.B)T (LHS) = (B)T.(A)T (RHS)")

LHS =
 [[23 51]
 [13 29]] 
RHS =
 [[23 51]
 [13 29]]
(A.B)T (LHS) = (B)T.(A)T (RHS)


In [74]:
# 2

"""
Equations:
2x - 3y + z = -1
 x - y + 2z = -3
3x + y -  z =  9

"""

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3,  1, -1]], dtype=float)

B = np.array([-1, -3, 9], dtype=float)

# AX = B
# X = A^-1 . B
# Finding X using np.linalg.inv()

A_inverse = np.linalg.inv(A)
X = A_inverse @ B
print("Using inverse matrix method:\n x = {:.2f}\n y = {:.2f}\n z = {:.2f}".format(X[0], X[1], X[2]))

Using inverse matrix method:
 x = 2.00
 y = 1.00
 z = -2.00


In [76]:
#3

X_solve = np.linalg.solve(A, B)
print("Using np.linalg.sovle():\n x = {:.2f}\n y = {:.2f}\n z = {:.2f}".format(X[0], X[1], X[2]))

Using np.linalg.sovle():
 x = 2.00
 y = 1.00
 z = -2.00


EXPERIMENT:

In [77]:
import time

# python lists
list1 = list(range(1000000))
list2 = list(range(1000000))

# numpy arrays
array1 = np.arange(1000000)
array2 = np.arange(1000000)

In [80]:
# 1

# python lists
start = time.time()
list_add = [list1[i] + list2[i] for i in range(1000000)]
end = time.time()
print("Time for element-wise addition of python lists:", end - start, "s")

# numpy arrays
start = time.time()
array_add = array1 + array2
end = time.time()

print("Time for element-wise addition of numpy arrays:", end - start, "s")

Time for element-wise addition of python lists: 0.23084712028503418 s
Time for element-wise addition of numpy arrays: 0.004932403564453125 s


In [79]:
# 2

# python lists
start = time.time()
list_multiply = [list1[i] * list2[i] for i in range(1000000)]
end = time.time()
print("Time for element-wise multiplication of python lists:", end - start, "s")

# numpy arrays
start = time.time()
array_multiply = array1 * array2
end = time.time()

print("Time for element-wise multiplication of numpy arrays:", end - start, "s")

Time for element-wise multiplication of python lists: 0.23586010932922363 s
Time for element-wise multiplication of numpy arrays: 0.0039119720458984375 s


In [83]:
# 3

# python lists
start = time.time()
list_dot = sum(list1[i] * list2[i] for i in range(1000000))
end = time.time()
print("Time for dot-product of python lists:", end - start, end="s\n")

# numpy arrays
start = time.time()
array_dot = np.dot(array1, array2)
end = time.time()

print("Time for dot-product of numpy arrays:", end - start, end="s\n")

Time for dot-product of python lists: 0.25112295150756836s
Time for dot-product of numpy arrays: 0.0021724700927734375s


In [89]:
# 4

# python matrices
python1 = [[1 for _ in range(1000)] for _ in range(1000)]
python2 = [[1 for _ in range(1000)] for _ in range(1000)]
start = time.time()
python3 = [[sum(python1[i][k] * python2[k][j] for k in range(1000))
           for j in range(1000)] for i in range(1000)]
end = time.time()

print("Time for python matrix multiplication:", end - start, "s")

# numpy matrices
np1 = np.ones((1000, 1000))
np2 = np.ones((1000, 1000))

start = time.time()
np3 = np1 @ np2
end = time.time()

print("Time for numpy matrix multiplication:", end - start, "s")

Time for python matrix multiplication: 55.20786905288696 s
Time for numpy matrix multiplication: 0.006860971450805664 s
